[tasks.install]
description = "Installs waswm in /usr/local/bin."
script = [
  "cargo build --release",
  "echo Installing in /usr/local/bin",
  "sudo mkdir -p /usr/local/bin",
  "sudo cp -f target/release/waswm /usr/local/bin",
  "sudo chmod 755 /usr/local/bin/waswm",

  "sudo mkdir -p /usr/local/share/xsessions",
  "sudo cp configuration/xsessions/waswm.desktop /usr/local/share/xsessions",
]

[tasks.xephyr]
description = "Tests the debug build inside xnest"
script = [
  "cargo build",
  "Xephyr -name 'waswm' -br -ac -noreset -screen 1024x768 +xinerama :2 &",
  "sleep 1 && RUST_LOG=debug DISPLAY=:2 exec target/debug/waswm"
]
