[package]
name = "coppe-wm"
version = "0.0.1"
authors = ["Mikhail Pogretskiy <mikhail.pogretskiy@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
env_logger = "0.9"
log = "0.4"
parking_lot = "0.11.2"
shlex = "1.0"
wasmer = "2.0"
x11rb = "0.9"
