[package]
name = "coppe-std"
version = "0.0.1"
authors = ["Mikhail Pogretskiy <mikhail.pogretskiy@gmail.com>"]
edition = "2018"

[dependencies]
coppe-core = { path = "../coppe-core" }
coppe-common = { path = "../../../coppe-common", features = [ "std" ] }
